### ISSUE TITLE
delight-nashorn-sandbox 0.0.5 Invalid MD5

### ISSUE THREAD

**Issue by philipborg** [javadelight/delight-main#1]
http://maven.appjangle.com/appjangle/releases/org/javadelight/delight-nashorn-sandbox/0.0.5/delight-nashorn-sandbox-0.0.5.pom.md5

Is invalid MD5 for

http://maven.appjangle.com/appjangle/releases/org/javadelight/delight-nashorn-sandbox/0.0.5/delight-nashorn-sandbox-0.0.5.pom

**Comment by objecthub-io** [comment]
This is true. It seems illegal MD5 files were generated. I have now updated the way that these hashes are created ([here a blog post on this](https://maxrohde.com/2016/08/15/generate-md5-hash-for-maven/)).

Could you try grabbing the 0.0.6 version of the Nashorn Sandbox and check if it works now?

Thanks!!

**Comment by philipborg** [comment]
Worked like a charm now on 0.0.6 using SBT (ivy2). I should be the one thanking you as well, as now I don't have to disable checksum check for my entire project. :+1:
